/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.instil.nativelibrary.android;

public class NativeLibrary {
  public static void Native_HelloWorld() {
    NativeLibraryJNI.Native_HelloWorld();
  }

  public static int Native_AddFunction(int arg0, int arg1) {
    return NativeLibraryJNI.Native_AddFunction(arg0, arg1);
  }

  public static void Native_PrintStructure(NativeObject arg0) {
    NativeLibraryJNI.Native_PrintStructure(NativeObject.getCPtr(arg0), arg0);
  }

}
