/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.instil.nativelibrary.android;

public class NativeObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NativeObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeLibraryJNI.delete_NativeObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setA(int value) {
    NativeLibraryJNI.NativeObject_a_set(swigCPtr, this, value);
  }

  public int getA() {
    return NativeLibraryJNI.NativeObject_a_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    NativeLibraryJNI.NativeObject_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return NativeLibraryJNI.NativeObject_message_get(swigCPtr, this);
  }

  public NativeObject() {
    this(NativeLibraryJNI.new_NativeObject(), true);
  }

}
